### ISSUE TITLE
Wrong colors in nord theme.

### ISSUE THREAD

**Issue by ad1tyawagh** [regolith-linux/regolith-styles#28]
Some colors in the *nord* theme are not as per the guidelines mentioned in https://www.nordtheme.com/docs/colors-and-palettes.

## References
https://github.com/arcticicestudio/nord-xresources/blob/develop/src/nord

**Comment by kgilmer** [comment]
This Regolith look (like all of them) is based on a color theme but doesn't claim 100% adherence to some set of color definitions.  In the case of Nord, as I recall there was a lack of a dark color for sufficient contrast so another color was added.  In any case, if you have a specific visual problem w/ the nord look which maps back to this issue, kindly describe it.  Otherwise there is no action we can take here, so will close.
